# Generated by Django 5.1.15 on 2026-08-19 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='CONFIRMED', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('payment_order_id', models.CharField(blank=True, max_length=255)),
                ('payment_signature', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='SUCCESS', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hospitals.hospital')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='doctors.appointmentslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'), models.Index(fields=['doctor', 'status'], name='bookings_bo_doctor__354590_idx')],
            },
        ),
    ]
