apiVersion: v1
kind: Secret
metadata:
  name: turna-secrets
  labels:
    app.kubernetes.io/name: turna
    app.kubernetes.io/part-of: turna-app
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "turna-prod-secret-key-change-me-in-production-!@#$981"
  POSTGRES_USER: "turna_user"
  POSTGRES_PASSWORD: "turna_secure_production_password_2026"
  DATABASE_URL: "postgres://turna_user:turna_secure_production_password_2026@turna-postgres:5432/turna_db"
