apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turna-postgres-pvc
  labels:
    app.kubernetes.io/name: turna-postgres
    app.kubernetes.io/part-of: turna-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
